platform :ios, '11.0'
use_frameworks!

target 'App' do
  # Add your Pods here

  #  Automatic Capacitor Pod dependencies, do not delete
  #  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  #  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'

  pod 'Capacitor', :patdh => '/Users/stewan/dev/capacitor'
  pod 'CapacitorCordova', :path => '/Users/stewan/dev/capacitor'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'

  # Do not delete
end
